### ISSUE TITLE
Need your help in my own project

### ISSUE THREAD

**Issue by ShivamPanchal** [Twitter-Sentiment-Analysis/R#1]
After running the code and getting the PIN, entering into the console, 
I have developed my own app.
I am getting the error

Error in function (type, msg, asError = TRUE)  : 
  Could not resolve host: 1.0

**Comment by sonali9696** [comment]
Is this in reference to the authentication.R code? The consumer key, consumer secret, access token and access secret is linked to our profile and provided by Twitter which might be causing the error. To create your very own Twitter application, register using the following steps: https://themepacific.com/how-to-generate-api-key-consumer-token-access-key-for-twitter-oauth/994/.
Feel free to get back to us once you are done.

**Comment by sonali9696** [comment]
Also, don't forget to download cacert.pem and keep it in the same folder as your code.  If you are behind a proxy they you have to set the proxy options in RCurl too(setting the proxy for the R is not enough). This command works
options( RCurlOptions = list(verbose = TRUE,proxy = "host:port"))

**Comment by ShivamPanchal** [comment]
Okay, thanks Sonali. I'll try this.
options( RCurlOptions = list(verbose = TRUE,proxy = "host:port"))
Maybe, it is the problem with the host.

**Comment by PoojaBabu** [comment]
I am trying to install twitteR , It seems it has lots of dependencies like installing 'curl'. I am trying to install 
libcurl4-openssl-dev, even that's not working. My R version is 3.3.1

**Comment by asmitapoddar** [comment]
Install the ROAuth and curl packages first. 
-> install.packages("ROAuth")
-> install.packages("curl")
You can run the following code to check which packages are already installed for you: 
ip <- as.data.frame(installed.packages()[,c(1,3:4)])
rownames(ip) <- NULL
ip <- ip[is.na(ip$Priority),1:2,drop=FALSE]
print(ip, row.names=FALSE)
Also you can try to disable your antivirus (if you have antivirus installed on your computer), and then try to install the package, as the antivirus can sometimes hamper the installation process.

**Comment by PoojaBabu** [comment]
Installing "ROAuth" failed. ERROR: configuration failed for package ‘RCurl’----and when tried to install "curl" , I get the following error
package ------------------------- ANTICONF ERROR ---------------------------
Configuration failed because libcurl was not found. Try installing:
 * deb: libcurl4-openssl-dev (Debian, Ubuntu, etc)
 * rpm: libcurl-devel (Fedora, CentOS, RHEL)
 * csw: libcurl_dev (Solaris)
When I try to install "libcurl4-openssl-dev", Rstudio outputs this **-package ‘libcurl4-openssl-dev’ is not available (for R version 3.3.1)**
I have no antivirus installed, I have also checked the existing packages, they are not found.

**Comment by asmitapoddar** [comment]
After the following step:
sudo apt-get install libcurl4-openssl-dev
you should do:
 install.packages("twitteR")
This should work.
The downloaded package should be in the directory:
‘/tmp/RtmpZ8TFBn/downloaded_packages’

**Comment by PoojaBabu** [comment]
I am using RStudio on my university Cluster. And I don't have permission to execute "sudo apt-get install libcurl4-openssl-dev" .

**Comment by PoojaBabu** [comment]
Also, our cluster runs on Cent OS, does it change any commands?

**Comment by PoojaBabu** [comment]
Hi, I have asked my professor. He is the administrator. So I got both libcurl and openssl package installed in linux. I could install twitteR and ROAuth now.
