### ISSUE TITLE
How to Run 

### ISSUE THREAD

**Issue by onetwoishan** [Twitter-Sentiment-Analysis/R#2]
How should i run these files

**Comment by asmitapoddar** [comment]
Install R on your machine. You have to run these files in R.

**Comment by adwivedi86** [comment]
cred$handshake(cainfo="cacert.pem")
Error in function (type, msg, asError = TRUE)  : 
  error setting certificate verify locations:
  CAfile: cacert.pem
  CApath: none

**Comment by adwivedi86** [comment]
how to remove this error

**Comment by asmitapoddar** [comment]
Even after receiving this message, if you run further code to access the tweets from Twitter using R, you usually are able to do so. Are you able to do so?

**Comment by sonali9696** [comment]
Make sure your certificate is in your current working directory. Re-check what's your current working directory by command in R

**Comment by nimraMalik** [comment]
where are those positive and negative text files?

**Comment by onetwoishan** [comment]
[negative-words.txt](https://github.com/Twitter-Sentiment-Analysis/R/files/1490118/negative-words.txt)
[positive-words.txt](https://github.com/Twitter-Sentiment-Analysis/R/files/1490119/positive-words.txt)

**Comment by nimraMalik** [comment]
library(ROAuth)
Error in library(ROAuth) : there is no package called ‘ROAuth’
> library(twitteR)
Error in library(twitteR) : there is no package called ‘twitteR’
> 
> consumer_key <-"AKJsxNqX2D8uTo9orgjRirvWL"
> consumer_secret <- "QOKk0ctHhbXNQ5QaipqofrZQzWM92mfkcoP60xe7HJzjSUCz6F"
> access_token<-"2617540074-5l6gGJhCP8iw9DS7sVD9qsFaUGfWGO9fqlHt5Wg"
> access_secret <- "VVMfNIzgPEUmCk5QyIWr5A4ZSC2Lxy7CERoUtWs4jAe0l"
> 
>  setup_twitter_oauth(consumer_key ,consumer_secret, access_token,  access_secret )
Error in setup_twitter_oauth(consumer_key, consumer_secret, access_token,  : 
  could not find function "setup_twitter_oauth"
>  
> cred <- OAuthFactory$new(consumerKey='AKJsxNqX2D8uTo9orgjRirvWL', consumerSecret='QOKk0ctHhbXNQ5QaipqofrZQzWM92mfkcoP60xe7HJzjSUCz6F',requestURL='https://api.twitter.com/oauth/request_token',accessURL='https://api.twitter.com/oauth/access_token',authURL='https://api.twitter.com/oauth/authorize')
Error: object 'OAuthFactory' not found

**Comment by nimraMalik** [comment]
Error in function (type, msg, asError = TRUE)  : 
  error setting certificate verify locations:
  CAfile: cacert.pem
  CApath: none

**Comment by nimraMalik** [comment]
where to paste the pincode in RStudio??


> 
> cred$handshake(cainfo="cacert.pem")
To enable the connection, please direct your web browser to: 
https://api.twitter.com/oauth/authorize?oauth_token=IxO26QAAAAAAwnS2AAABX90y-es
When complete, record the PIN given to you and provide it here: #After this you will be redirected to a URL where you click on authorize app and get the passkey to be entered in RStudio
Error: Authorization Required

**Comment by nimraMalik** [comment]
Error in data.frame(table1$Text, table1$value, table2$value, table3$value) : 
  object 'table1' not found
> 
> #Histogram
> hist(table_final$Positive, col=rainbow(10))
Error in hist(table_final$Positive, col = rainbow(10)) : 
  object 'table_final' not found
> hist(table_final$Negative, col=rainbow(10))
Error in hist(table_final$Negative, col = rainbow(10)) : 
  object 'table_final' not found
> hist(table_final$Score, col=rainbow(10))
Error in hist(table_final$Score, col = rainbow(10)) : 
  object 'table_final' not found
> 
> #Pie
> slices <- c(sum(table_final$Positive), sum(table_final$Negative))
Error: object 'table_final' not found

**Comment by nimraMalik** [comment]
how to solve this error
Object not found

**Comment by nimraMalik** [comment]
Thank you so much, but i have another question. When i run the code, the
error of "Object not found" appears at the console. How to resolve this
error??
Please reply me as soon as possible....


[image: Inline image 1]

**Comment by onetwoishan** [comment]
code for forming table is not getting executed mostly
try to execute code where table_final is getting created

**Comment by nimraMalik** [comment]
code is now working perfectly, thank you so much

**Comment by nimraMalik** [comment]
i have to do a project on Cryptography and network security in which
Machine Learning techniques must be used. Do you have any idea about this
kind of project?
