### ISSUE TITLE
how to resolve this error

### ISSUE THREAD

**Issue by adwivedi86** [Twitter-Sentiment-Analysis/R#3]
Error in function (type, msg, asError = TRUE)  : 
  error setting certificate verify locations:
  CAfile: cacert.pem
  CApath: none

**Comment by sonali9696** [comment]
There is a path problem of the certificate. Re-check your current working directory by R command, and make sure that the certificate is in your current working directory.
Secondly, even after receiving this message, if you run further code to access the tweets from Twitter using R, you usually are able to do so.
