### ISSUE TITLE
Need help running the project

### ISSUE THREAD

**Issue by amanver16** [Twitter-Sentiment-Analysis/R#5]
Hi there, Thanks for uploading this project. I'm new to R programming but i've got the sentiment analysis as a college project in R. After lots of digging i ended up here and your project is quite understandable for me. Since i'm new, please guide me how should i run this project. I tried running it in r studio by opening the script_running.r file. But i got some errors like package is not found. Please tell me the appropriate way to run the project. Your help will be really appreciable. Thanks :) @asmitapoddar @sonali9696

**Comment by sonali9696** [comment]
You can simply open the script file and click "run all" from the menu bar.

**Comment by amanver16** [comment]
Thanks. My actual problem is i'm getting the following error.
_**To enable the connection, please direct your web browser to: 
https://api.twitter.com/oauth/authorize?oauth_token=4mHa0QAAAAAAwnS2AAABX-owtyE
When complete, record the PIN given to you and provide it here: #After this you will be redirected to a URL where you click on authorize app and get the passkey to be entered in RStudio
Error: Authorization Required**_

I t redirects me to a webpage where it says you don't have access to getfeeds10.
So please tell me how to get the pass key for RStudio as its asking in above error.
@sonali9696 @asmitapoddar

**Comment by sonali9696** [comment]
You would need to learn how to do ROAuth authentication to access twitter api. You have to visit twitter developer website and make your own getFeeds. This one is ours so you don't have access.

You would be able to find multiple blogs for the same.

**Comment by khayalghosh** [comment]
where will we have to enter PIN(7-digit) to complete authorization process.

**When complete, record the PIN given to you and provide it here: #After this you will be redirected to a URL where you click on authorize app and get the passkey to be entered in RStudio
Error: Authorization Required**

**Comment by sonali9696** [comment]
When the prompt appears, the cursor is right at "provide it here". That's exactly where you need to provide. Pressing enter without providing the pin would give the above error.
