### ISSUE TITLE
Opening URL

### ISSUE THREAD

**Issue by gwene159** [Twitter-Sentiment-Analysis/R#7]
Hi, I am new to R programming so pardon me if I am too ignorant :(  I tried to run "script_running.R" file but I have an error as below. Could you please help me out what is the problem?

When I tried to run at the beginning of the code, it gives me an error below.

`>  setup_twitter_oauth(consumer_key ,consumer_secret, access_token,  access_secret )`
**[1] "Using direct authentication"
Error in check_twitter_oauth() : OAuth authentication error:
This most likely means that you have incorrectly called setup_twitter_oauth()'**

**Comment by ghost** [comment]
install base64enc library

**Comment by asmitapoddar** [comment]
Learn how to do ROAuth authentication to access the Twitter API. You have to visit Twitter Developer website and make your own Twitter authentication. This one is ours so you don't have access.

There are many blogs available to understand how to do this.
